### ISSUE TITLE
Review #1: Mistake in fig. 2  (model-space lattice)

### ISSUE THREAD

**Issue by mickymuis** [mickymuis/vouwpapier#3]
Reviewer #1 commented they believe fig. 2 is incomplete, they write: 

> for instance, the model H={ V=[0 1], W=[1 O]} and I = [[W .] [V .]]
  is not in the lattice. This model could be obtained from the topmost model of 2nd column,   building a pattern W = [0 1] = (/) (X * (0,0) + Y * (1,0))

Suggestions:
- Verify this
- Fix if necessary, should be easy enough but I'm wary for the extra space requirements.

**Comment by mickymuis** [comment]
After looking carefully I had to agree with the reviewer. This means that 6 more permutations had to be added to a figure that was already quite large. After literally hours of fighting with LaTeX I managed to fit the extra six into the existing space. I think it looks quite nice albeit a little crammed. I will go over this once again to double check for any mistakes.

**Comment by mleeuwen** [comment]
Good!
(In case of space issues, you could consider leaving out part of the lattice while leaving some links to the omitted part, so that it is clearly indicated that the depicted lattice is incomplete.)
