### ISSUE TITLE
Review #2: related to local pattern mining in graphs

### ISSUE THREAD

**Issue by mickymuis** [mickymuis/vouwpapier#5]
Reviewer #2, who is apparently very much in favor of the paper, thinks the problem is related to local pattern mining in graphs. He suggests two things:
(1) Acknowledge it
(2) Elaborate on it

Unfortunately another maybe-related problem. I have thought about similarities with graph mining already and I believe this was also discussed at some point. The relation is definitely there, as we could define our problem as a very specific class of graphs. I would really like some input if it has merit to do anything with this. Acknowledging it seems not too much trouble, so perhaps we should do that anyway.

**Comment by mleeuwen** [comment]
I think we could mention the relationship somewhere, either in the Intro or RelWork, but without giving a lot of details. Our geometric grids are a very specific type of graphs; it might be useful to briefly argue that generic frequent graph mining algorithms cannot be straightforwardly applied to our data, at least not as effectively and/or efficiently? (I would expect this to be the case.)

**Comment by mickymuis** [comment]
I believe we have covered this by mentioned the GriMa paper and saying that our problem is different from graph mining in related work.
